### ISSUE TITLE
Chapter 2: Auth using JWT's 'UserManager' object has no attribute 'get_object_by_public_id'

### ISSUE THREAD

**Issue by the-garth** [PacktPublishing/Full-stack-Django-and-React#52]
I'm currently on Chapter 2 of your book where i'm building out the Auth and getting the user.

I've got to the point where i am trying to use the API to call the users and individual user:
When i hit `http://127.0.0.1:8000/api/user` i successfully return all users
``` json
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": "07c123cefa79459f9f68b6d2455b8f77",
            "username": "john-doe",
            "first_name": "John",
            "last_name": "Doe",
            "email": "testuser@yopmail.com",
            "is_active": true,
            "created": "2023-10-17T11:17:47.242594Z",
            "updated": "2023-10-17T11:17:47.242600Z"
        }
    ]
}
```

When i hit `http://127.0.0.1:8000/api/user/07c123cefa79459f9f68b6d2455b8f77` it throws this error:
```bash
AttributeError: 'UserManager' object has no attribute 'get_object_by_public_id'
```

I can't find anything online on how to fix this, any ideas what's going wrong?
My User model,  serializers and viewsets look like this:
**User Model**
```python
from django.db import models
import uuid
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, UserManager
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist

# Create your models here.


class User(AbstractBaseUser, PermissionsMixin):
    public_id = models.UUIDField(
        db_index=True, unique=True, default=uuid.uuid4, editable=False)
    username = models.CharField(db_index=True, max_length=255, unique=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(db_index=True, unique=True)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    last_login = models.DateTimeField(auto_now_add=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    objects = UserManager()

    def __str__(self):
        return f"{self.email}"

    @property
    def name(self):
        return f"{self.first_name} {self.last_name}"


class UserManager(BaseUserManager):
    def get_object_by_public_id(self, public_id):
        try:
            instance = self.get(public_id=public_id)
            return instance
        except (ObjectDoesNotExist, ValueError, TypeError):

            return Http404

    def create_user(self, username, email, password=None, **kwargs):
        """
        Create and return a `User` with an email, phone_number, username, password.
        """
        if username is None:
            raise TypeError('Users must have a username')
        if email is None:
            raise TypeError('Users must have ab email')
        if password is None:
            raise TypeError('Users must have a password')

        user = self.model(username=username,
                          email=self.normalize_email(email), **kwargs)
        user.save(using=self._db)
        return user

    def create_super_user(self, username, email, password, **kwargs):
        """
        Create and return a `User` with superuser (admin) permissions.
        """
        if password is None:
            raise TypeError('Superuser must have a password')
        if email is None:
            raise TypeError('Superuser must have an email')
        if username is None:
            raise TypeError('Superuser must have a username')

        user = self.create_user(username, email, password, **kwargs)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user

```

**User Viewsets**
``` python
from rest_framework.permissions import AllowAny, BasePermission
from rest_framework import viewsets
from core.user.serializers import UserSerializer
from core.user.models import User


class UserViewSet(viewsets.ModelViewSet):
    http_method_names = ('patch', 'get')
    # using AllowAny + BasePermission to allow bypassing of permissions correctly
    permission_classes = (AllowAny, BasePermission)
    serializer_class = UserSerializer

    def get_queryset(self):
        if self.request.user.is_superuser:
            return User.objects.all()
        return User.objects.exclude(is_superuser=True)

    def get_object(self):
        obj = User.objects.get_object_by_public_id(self.kwargs['pk'])
        self.check_object_permissions(self.request, obj)
        return obj

```

**User Serializers**
``` python
from rest_framework import serializers
from core.user.models import User


class UserSerializer(serializers.ModelSerializer):
    id = serializers.UUIDField(
        source='public_id', read_only=True, format='hex')
    created = serializers.DateTimeField(read_only=True)
    updated = serializers.DateTimeField(read_only=True)

    class Meta:
        model = User
        fields = [
            'id',
            'username',
            'first_name',
            'last_name',
            'email',
            'is_active',
            'created',
            'updated'
        ]
        read_only_field = ['is_active']

```

Full error output:
```bash
Internal Server Error: /api/user/07c123cefa79459f9f68b6d2455b8f77/
Traceback (most recent call last):
  File "/Users/gareth/Development/django-social/social/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gareth/Development/django-social/social/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gareth/Development/django-social/social/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gareth/Development/django-social/social/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gareth/Development/django-social/social/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gareth/Development/django-social/social/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/gareth/Development/django-social/social/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/gareth/Development/django-social/social/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gareth/Development/django-social/social/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 54, in retrieve
    instance = self.get_object()
               ^^^^^^^^^^^^^^^^^
  File "/Users/gareth/Development/django-social/social/core/user/viewsets.py", line 21, in get_object
    obj = User.objects.get_object_by_public_id(self.kwargs['pk'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UserManager' object has no attribute 'get_object_by_public_id'
```

**Packages Versions:**
Django==4.2.6
psycopg2_binary==2.9.9
djangorestframework==3.14.0
django-filter==23.3
djangorestframework-simplejwt==5.3.0

**Comment by the-garth** [comment]
I've managed to fix it, my `UserManager` class needed to come before my `User` class in the `user/models.py` file

also the line `return Http404` in the method `get_object_by_public_id` throws and attribute error:
```bash
AttributeError: Got AttributeError when attempting to get a value for field `username` on serializer `UserSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `type` instance.
Original exception text was: type object 'Http404' has no attribute 'username'.
```

this needed to be changed to be `raise` instead of `return`
``` python
    def get_object_by_public_id(self, public_id):
        try:
            instance = self.get(public_id=public_id)
            return instance
        except (ObjectDoesNotExist, ValueError, TypeError):
            raise Http404
```
